# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'd08' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for d08
  pod 'tfleming2017', :path => '../tfleming2017'
end
